### ISSUE TITLE
examples/go: client_chat_message_stream.go does not compile (signature drift, uncaught by CI)

### ISSUE THREAD

**Issue by shyd0w** [ekoDB/ekodb-client#179]
`examples/go/client_chat_message_stream.go` does not compile. Found while verifying
an unrelated `go mod tidy` in #178; confirmed pre-existing on `origin/main` both
before and after that change.

## Reproduction

```
$ cd examples/go
$ go build -o /dev/null client_chat_message_stream.go
# command-line-arguments
./client_chat_message_stream.go:49:59: not enough arguments in call to client.ChatMessageStream
	have (string, ekodb.ChatMessageRequest)
```

60 of the 61 files in `examples/go` compile individually; this is the only one that
does not.

## Cause

The example calls `client.ChatMessageStream` with `(string, ChatMessageRequest)`,
but the method's signature has since gained at least one more parameter. The
example was not updated with it, so client and example have drifted.

## Why this is worth fixing rather than noting

An example that does not compile is a broken published artifact — this is the
reference material users copy from. It also means nothing in CI compiles these
files, or this would have been caught at the commit that changed the signature.

Two parts to the fix:

1. Update the call to match the current signature.
2. **Add a compile check for `examples/go` to CI**, so the class of defect cannot
   recur silently. Note `go build ./...` does NOT work here: every example declares
   its own `func main()` in one package, so the package-level build fails with
   `main redeclared` regardless of correctness. The check has to compile each file
   individually, which is what surfaced this:

   ```bash
   for f in examples/go/*.go; do go build -o /dev/null "$f" || exit 1; done
   ```

   The existing `test-examples-go` target runs the examples against a live server,
   so it cannot catch a compile break without one.

## Acceptance criteria

- [ ] `client_chat_message_stream.go` compiles
- [ ] The call matches the current `ChatMessageStream` signature
- [ ] A per-file compile check for `examples/go` runs in CI
- [ ] That check is proven to FAIL on the broken version before the fix (so it is a real guard, not a vacuous pass)
- [ ] CHANGELOG entry

**Comment by shyd0w** [comment]
Review on #180 supplied the missing argument for why the **existing** build target cannot be fixed in place, so the per-file compile loop proposed here is the right shape rather than one option among several.

The `Makefile` target tolerates failure explicitly:

```
|| echo "⚠️ Go examples failed (expected)"
```

That is honest about `go build ./...` being structurally unable to succeed here — 60 files each their own `package main`, so `main redeclared` fires regardless of dependency state — but the consequence is that **a real break and the structural noise render identically**. The module has no build signal at all. That is why this compile failure has been sitting on the default branch unnoticed rather than failing something.

So the guard cannot be "make `go build ./...` pass"; it has to be the per-file loop, which costs one iteration and turns the target into something that can fail for a reason.

Two verified facts to save the next person re-deriving them:

- **Exactly one of the 60 files fails**, at `origin/main` and on #180's head alike, with the same error. The full signature is `want (context.Context, string, ekodb.ChatMessageRequest)` against `have (string, ekodb.ChatMessageRequest)` — a missing leading `context.Context`.
- **`go mod tidy` is unaffected by the break.** A wrong argument count is a type error, not an import error, so the import graph tidy walks is untouched; tidy exits 0 and changes nothing. Relevant because it means this ticket does not block dependency work on the module.

Also worth noting for whoever picks this up: the relative `replace` directive in `examples/go/go.mod` points at a sibling of this repository, so any CI job or local reproduction has to place that module at the matching relative position before running Go commands, or it fails in a way that looks like a dependency problem and is not.

**Comment by shyd0w** [comment]
Ready for review, on PR #240 (branch fix/sdk-contract-backlog).

**What changed:**
- The actual signature drift in `client_chat_message_stream.go` was already fixed by an earlier commit on this branch (5d4a829) before this pass -- found while re-verifying this ticket, not new work.
- What was missing: a CI guard. `scripts/run-client-examples.sh check go` already compiles every `examples/go/*.go` individually via a temp `-modfile` overlay, but nothing in CI called it. Added a job (`check-go-examples-compile` in `.github/workflows/examples-inventory.yml`) that checks out `ekodb-client-go` as a sibling and runs it (6d2d609).
- Also added a daily `schedule:` trigger, since this class of drift originates in `ekodb-client-go` and touches no path this repo's push/pull_request triggers watch.
- CHANGELOG entry added (`ekodb_client/CHANGELOG.md`).

**How to verify:** reverted the fixed call locally and confirmed the new job's check goes red on the exact original compile error, then green again on the current code (details in the PR's review thread). CI itself will exercise the real GitHub Actions path once merged.

**Acceptance criteria status:** all four met -- compiles, matches the current signature, CI guard added and proven to fail before the fix, CHANGELOG entry present.

**Comment by shyd0w** [comment]
Follow-up: the CI job itself had a real bug — it checked out ekodb-client-go's default branch unconditionally, but this PR's examples need APIs that only exist on ekodb-client-go's own `fix/sdk-contract-backlog` branch (its PR #83, not yet merged). That made the new job fail on this exact PR every time. Fixed at 908d863: resolves a same-named branch on ekodb-client-go first, falls back to its default branch otherwise. Reproduced the failure against a real clone of ekodb-client-go's origin/main, confirmed red-then-green.
